### ISSUE TITLE
Error when using Install-Module: The following commands are already available on this system:'Write-Host'

### ISSUE THREAD

**Issue by franklesniak** [picrap/FIGlet#3]
When installing the module, I receive an error:

```
PS C:\Users\flesniak> Install-Module Figlet
Install-Package: C:\program files\powershell\7\Modules\PowerShellGet\PSModule.psm1:9709
Line |
9709 |  … talledPackages = PackageManagement\Install-Package @PSBoundParameters
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The following commands are already available on this system:'Write-Host'. This module 'Pansies' may
     | override the existing commands. If you still want to install this module 'Pansies', use -AllowClobber
     | parameter.
```

Ideally, the module should be designed without a command conflict so that it does not throw this message. I am on Windows 10 2004 x64, English-US, PowerShell v7.0.2.

Thanks!

**Comment by franklesniak** [comment]
Actually, my apologies. I just realized that this error is resulting from the Pansies module (a dependency), not Figlet.

Still, a mention of this and the required workaround (i.e., how to best install the module) would be welcome in readme.md.

Thanks again!

**Comment by picrap** [comment]
I also did not write the figlet powershell module :)
